# Generated by Django 4.1.3 on 2022-11-30 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=255)),
                ("user_email", models.EmailField(max_length=254)),
                ("user_password", models.CharField(max_length=255)),
            ],
        ),
    ]
