# Generated by Django 4.1.3 on 2022-11-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("json_main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="user_email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
